app/forum/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, MultipleFileField, SelectField, FileField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length

class PostForm(FlaskForm):
    content = TextAreaField('Say something', validators=[DataRequired()])
    submit = SubmitField('Post')

class ThreadForm(PostForm):
    title = StringField('Title', validators=[DataRequired()])

class DeleteForm(FlaskForm):
    submit = SubmitField('Delete')

app/forum/__init__.py
from flask import Blueprint

bp = Blueprint('forum', __name__)

from app.forum import views

app/forum/views.py
"""
Routes and views for the flask application.
"""

from flask import render_template, request, flash, redirect, url_for, jsonify, make_response
from flask_login import current_user, login_user, logout_user, login_required
from flask_mail import Message
from app import db, mail
from app.forum import bp
from app.models import User, Question, Option, Response, Group, Thread, Post, Proficiency, Quiz
from app.forum.forms import *
from app.base import *
from app.forum.forum import *
from app.decorator import check_confirmed

# Routes for Class Forum
# forum
# forum/thread
# forum/thread/<int:threadID>
# forum/thread/<int:threadID>/delete
# forum/thread/<int:threadID>/<int:postID>/delete
# forum/thread/<int:threadID>/<int:postID>/edit
@bp.route('/<int:groupID>')
@bp.route('/<int:groupID>/forum')
@login_required
def forum(groupID):
    group = validate_group_link(current_user, groupID)
    if group is None:
        return redirect(url_for('main.dashboard'))
    threads = Thread.query.filter_by(groupID=groupID).all()
    image_file = get_image_file(current_user)
    return render_template('forum/forum.html', title=' | Forum', groupID=groupID, threads=threads, group=group, image_file=image_file)

@bp.route('/<int:groupID>/forum/thread', methods=['GET','POST'])
@login_required
def create_thread(groupID):
    # Check validity of link access first
    group = validate_group_link(current_user, groupID)

    # Render ThreadForm
    form = ThreadForm()

    # POST request for new thread
    if form.validate_on_submit():
        thread = add_thread(current_user, group, form.title.data, form.content.data)     
        return redirect(url_for('forum.forum_post', groupID=groupID, threadID=thread.id))

    # GET request for create thread
    return render_template('forum/posts.html', title=' | Forum', postForm=form)

@bp.route('/<int:groupID>/forum/thread/<int:threadID>', methods=['GET', 'POST'])
@login_required
def forum_post(groupID, threadID):
    # Check validity of link access first
    group = validate_group_link(current_user, groupID)
    thread = Thread.query.filter_by(groupID=groupID,id=threadID).first_or_404()

    # Render Posts and PostForm
    posts = Post.query.filter_by(threadID=threadID).all()
    users = get_post_users(posts)

    postForm = PostForm()
    delThreadForm = DeleteForm(prefix="thread")
    delPostForm = DeleteForm(prefix="post")

    # POST request for new post
    if postForm.validate_on_submit():
        save_post(current_user, postForm.content.data, threadID)
        return redirect(url_for('forum.forum_post',groupID=groupID,threadID=threadID))
    
    # GET request for forum thread
    return render_template('forum/posts.html', title=' | Forum', thread=thread,posts=posts, postForm=postForm, delThreadForm=delThreadForm, delPostForm=delPostForm, users=users)

@bp.route('/<int:groupID>/forum/thread/<int:threadID>/delete', methods=['POST'])
@login_required
def delete_thread(groupID, threadID):
    # Check validity of link access first
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403

    group = validate_group_link(current_user, groupID)
    thread = Thread.query.filter_by(groupID=groupID,id=threadID).first_or_404()

    postForm = PostForm()
    delThreadForm = DeleteForm(prefix="thread")
    delPostForm = DeleteForm(prefix="post")

    if delThreadForm.validate_on_submit():
        remove_thread(thread)
        flash('Thread deleted')
        return redirect(url_for('forum.forum', groupID=groupID))

@bp.route('/<int:groupID>/forum/thread/<int:threadID>/<int:postID>/delete', methods=['POST'])
@login_required
def delete_post(groupID, threadID, postID):
    # Check validity of link access first
    post = validate_post_link(current_user, groupID,threadID,postID)
    if post is None:
        return render_template('errors/error403.html'), 403
    postForm = PostForm()
    delThreadForm = DeleteForm(prefix="thread")
    delPostForm = DeleteForm(prefix="post")
    if delPostForm.validate_on_submit():
        remove_post(post)
        return redirect(url_for('forum.forum_post', groupID=groupID,threadID=threadID))

@bp.route('/<int:groupID>/forum/thread/<int:threadID>/<int:postID>/edit', methods=['GET','POST'])
@login_required
def edit_post(groupID,threadID,postID):
    # Check validity of link access first
    post = validate_post_link(current_user, groupID,threadID,postID)
    if post is None:
        return render_template('errors/error403.html'), 403

    form = PostForm()
    if request.method == 'GET':
        form.content.data=post.content

    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        return redirect(url_for('forum.forum_post', groupID=groupID,threadID=threadID))

    return render_template('forum/posts.html', title=' | Forum', postForm=form, editpost=post)

app/templates/forum/forum.html
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='content/forumstyle.css') }}">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
{% endblock %}
{% block content %}
{% include "sidebar.html" %}
<main class="forum-grid">
    <div class="forum-header">
        <h1>{{ group.name }} FORUM</h1>
        <a href="{{ url_for('forum.create_thread',groupID=groupID) }}"><h5><i class="fas fa-plus"> Create A New Thread</i></h5></a>
    </div>
    <div class="forum-title">
        <h2>Post Title</h2>
    </div>
    <div class="forum-count">
        <h2>Number of Posts</h2>
    </div>
    <div class="forum-time">
        <h2>Last Post</h2>
    </div>
</main>
{% for thread in threads %}
<div class="threads-grid">
    <div class="post-title {{ loop.cycle('odd', 'even') }}">
        <a href="{{ url_for('forum.forum_post', groupID=groupID, threadID=thread.id) }} ">
            <h1>{{ thread.title }}</h1>
        </a>
    </div>
    <div class="post-count {{ loop.cycle('odd', 'even') }}">
        <h1>{{ thread.posts | length }}</h1>
    </div>
    <div class="time-stamp {{ loop.cycle('odd', 'even') }}">
        <h1>{{ thread.timestamp }}</h1>
    </div>
</div>
{% endfor %}
{% endblock %}

app/templates/forum/posts.html
{% from "_formhelpers.html" import render_error %}
﻿{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='content/poststyle.css') }}">
{% endblock %}
{% block content %}
<div>
    {% if thread %}
    <div class="thread-title">
        <a class="thread-back" href="{{url_for('forum.forum', groupID=thread.groupID)}}"><i class="far fa-arrow-alt-circle-left"></i>B a c k</a>
        <h1 class="thread-title-text"> {{ thread.title }} </h1>
        {% if current_user.urole == 'educator' %}
        <a class="thread-delete">
            <form action="{{ url_for('forum.delete_thread', groupID=thread.groupID,threadID=thread.id) }}" method="post" class="create-form">
                {{ delThreadForm.hidden_tag() }}
                <i class="fas fa-trash-alt"></i>{{ delThreadForm.submit() }}
            </form>
        </a>
        {% endif %}
    </div>
    {% if not editpost %}

    {% for post in posts %}
    <div class="post-content">
        <h2 class="name">{{ users[post.userID] }}</h2>
        {% if current_user.id == post.userID or current_user.urole == 'educator' %}
        <a class="post-delete">
            <form action="{{ url_for('forum.delete_post', groupID=thread.groupID,threadID=thread.id,postID=post.id) }}" method="post" class="create-form">
                {{ delPostForm.hidden_tag() }}
                <i class="fas fa-trash-alt"></i>{{ delPostForm.submit() }}
            </form>
        </a>
        <a class="post-edit" href="{{url_for('forum.edit_post',groupID=thread.groupID,threadID=thread.id,postID=post.id)}}"><i class="far fa-edit"></i>Edit Post</a>
        {% endif %}

        <div class="content"> {{ post.content }} </div>
    </div>
    {% endfor %}

    {% endif %}
    {% endif %}

    

    <div class="form-container">
        <div class="post-form">
            <h1 class="form-heading">Post An Announcement/Question!</h1>
            <form action="" method="post">
                {{ postForm.hidden_tag() }}
                {% if postForm.title %}
                <div class="post-heading">
                    <h1>Create A New Post</h1>
                </div>

                <div class="input-container">
                    {{ postForm.title() }}
                    {{ postForm.title.label }}
                    <!--render_error(form.title)-->
                    <div class="underline"></div>
                </div>
                {% endif %}
                <div class="input-container">
                    {{ postForm.content(cols=37, rows=8, class_="textarea", placeholder="Enter your message!") }}
                    <!--render_error(form.content)-->
                </div>
                {{ postForm.submit(class_="post-btn") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}