app/quiz/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, MultipleFileField, SelectField, FileField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length

from app.models import User, Topic


class QuestionForm(FlaskForm):
    topic = SelectField('Select Topic', validators=[DataRequired()], coerce=int)
    qn = StringField('Input Question', validators=[DataRequired()])
    op1 = StringField('Option 1', validators=[DataRequired()])
    op2 = StringField('Option 2', validators=[DataRequired()])
    op3 = StringField('Option 3', validators=[DataRequired()])
    op4 = StringField('Option 4', validators=[DataRequired()])
    corrOp = SelectField('Correct Option', choices=[(0, 'Select Correct Option'), \
        (1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], validators=[DataRequired()], coerce=int)
    img = FileField('Attach Image', validators=[FileAllowed(['jpeg', 'svg', 'jpg', 'png'], 'File Type not allowed, only image file types permitted!')])
    submit = SubmitField('Save and Add New Question')
    complete = SubmitField('Save and Complete Quiz')

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.topic.choices = [(topic.id, topic.name) for topic in Topic.query.all()]

class StringFormMixin():
    title = StringField('String', validators=[DataRequired()])

class CodeForm(FlaskForm, StringFormMixin):
    submit = SubmitField('View Progress Report')

class NameForm(FlaskForm, StringFormMixin): 
    submit = SubmitField('Create')

class DeleteForm(FlaskForm):
    submit = SubmitField('Delete')

class ReattemptForm(FlaskForm):
    submit = SubmitField('Reattempt Quiz')

class QuizClassForm(FlaskForm):
    submit = SubmitField('Add Quiz to Class')

app/quiz/__init__.py
from flask import Blueprint

bp = Blueprint('quiz', __name__)

from app.quiz import views

app/quiz/views.py
"""
Routes and views for the flask application.
"""

from flask import render_template, request, flash, redirect, url_for, jsonify, make_response
from flask_login import current_user, login_user, logout_user, login_required
from flask_mail import Message
from app import db, mail
from app.quiz import bp
from app.models import User, Question, Option, Response, Group, Thread, Post, Proficiency, Quiz
from app.quiz.forms import *
from app.base import *
from app.quiz.questions import *
from app.decorator import check_confirmed



# Routes for quiz administration
# create
# /<int:quizID>
# success
# question
# question/<int:qnID>/delete
# question/<int:qnID>/edit
@bp.route('/create', methods=['POST'])
@login_required
def createquiz():
    """Renders the create quiz page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    classForm = NameForm(prefix='class')
    quizForm = NameForm(prefix='quiz')
    image_file = get_image_file(current_user)
    if quizForm.validate_on_submit():
        quiz = add_quiz(current_user, quizForm.title.data)
        if quiz is None:
            flash('You have already created a Quiz with this name. Please choose a different name.', 'warning')
            return redirect(url_for('main.dashboard'))
        return redirect(url_for('quiz.createqn', quizID=quiz.id))
    return render_template('dashboard.html', image_file=image_file, classForm=classForm, quizForm=quizForm)

@bp.route('/<int:quizID>/delete', methods=['POST'])
@login_required
def deletequiz(quizID):
    """Renders the create quiz page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_link(current_user, quizID)
    delQuizForm = DeleteForm(prefix='quiz')
    delQnForm = DeleteForm(prefix='qn')
    if delQuizForm.validate_on_submit():
        remove_quiz(quiz)
        flash('Quiz deleted')
        return redirect(url_for('main.dashboard'))


@bp.route('/<int:quizID>/success')
@login_required
def createquizsuccess(quizID):
    """Renders the create quiz was a success page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403

    return render_template('quiz/createquizsuccess.html', title=' | Create Quiz', quizID=quizID)

@bp.route('/<int:quizID>')
@login_required
def preview_quiz(quizID):
    """Renders the preview quiz page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_link(current_user, quizID)
    questions = get_questions_quiz(quiz)
    delQuizForm = DeleteForm(prefix='quiz')
    delQnForm = DeleteForm(prefix='qn')
    return render_template('quiz/previewquiz.html', title=' | Create Class', questions=questions, quiz=quiz, delQuizForm=delQuizForm, delQnForm=delQnForm)

@bp.route('/<int:quizID>/question', methods=['GET', 'POST'])
@login_required
def createqn(quizID):
    """Renders the add questions page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_link(current_user, quizID)
    form = QuestionForm()
    delQuizForm = DeleteForm(prefix='quiz')
    delQnForm = DeleteForm(prefix='qn')
    if form.validate_on_submit():
        #Commit inputs to database
        options = (form.op1.data, form.op2.data, form.op3.data, form.op4.data)
        question = add_question(current_user, form.qn.data, options, form.corrOp.data, form.topic.data)
        if form.img.data:
            question.image_file = update_qn_image(form.img.data)
        add_question_quiz(quiz, question)
        flash('Question added')
        if form.complete.data:
            return redirect(url_for('quiz.createquizsuccess', quizID=quizID))
        return redirect(url_for('quiz.createqn', quizID=quizID))

    return render_template('quiz/createqn.html', title=' | Create Quiz', form=form, quiz=quiz,delQuizForm=delQuizForm, delQnForm=delQnForm)

@bp.route('/<int:quizID>/question/<int:qnID>/delete', methods=['POST'])
@login_required
def deleteqn(quizID, qnID):
    """Routing to delete a question from a quiz for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_link(current_user, quizID)
    qn = validate_qn_link(qnID, current_user.id)
    delQuizForm = DeleteForm(prefix='quiz')
    delQnForm = DeleteForm(prefix='qn')
    if delQnForm.validate_on_submit():
        remove_question_quiz(quiz, qn)
        flash('Question removed from Quiz')
        return redirect(url_for('quiz.preview_quiz', quizID=quizID))

@bp.route('/question/<int:qnID>/edit', methods=['GET', 'POST'])
@login_required
def editqn(qnID):
    """Renders the edit questions page for educators."""
    if not current_user.check_educator():
        return render_template('errors/error403.html'), 403
    qn = validate_qn_link(qnID, current_user.id)
    form = QuestionForm()

    if request.method == 'GET':
        topicID = qn.topicID if qn.topicID else 0
        form.topic.data = topicID
        form.qn.data = qn.question
        options = [option.option for option in qn.options]
        form.op1.data, form.op2.data, form.op3.data, form.op4.data = options
        for i in range(len(options)):
            if qn.options[i].id == qn.answerID:
                form.corrOp.data = i + 1
                break

    if form.validate_on_submit():
        #Commit inputs to database
        options = (form.op1.data, form.op2.data, form.op3.data, form.op4.data)
        edit_question(qn, form.qn.data, options, form.corrOp.data, form.topic.data)
        flash('Question Edited Successfully!')
        return redirect(url_for('main.dashboard'))

    return render_template('quiz/createqn.html', title=' | Create Quiz', form=form, edit=True)


# Routes for Quiz attempts
# quiz
# quiz/<int:quizID>/<int:qnNum>
# quiz/result
# quiz/<int:quizID>/result
@bp.route('/tailored/', methods=['GET', 'POST'])
@bp.route('/tailored/<int:attempt>', methods=['GET', 'POST'])
@login_required
def quiz(attempt=None):
    '''Renders tailored quiz'''
    # Gets a student CAT object for the user
    prof, student = get_student_cat(current_user, 1, attempt)

    # If enough questions already attempted, go to result
    try:
        if student.stop():
            add_proficiency(current_user)
            return redirect(url_for('quiz.result'))
    except ValueError:
        return redirect(url_for('quiz.result'))

    # If attempting the quiz, get the next unanswered question to display
    if request.method == 'GET':
        question, options = student.get_question_options()
        if question is None:
            flash('Sorry, no more questions!')
            return redirect(url_for('quiz.result'))
        return render_template('quiz/quiz.html', question=question, options=options, attempt=attempt)

    # If submitting an attempted question
    elif request.method == 'POST':
        submit_response(current_user, request.form)
        return redirect(url_for('quiz.quiz',attempt=attempt))

### UNTESTED
@bp.route('/tailored/reattempt', methods=['POST'])
@login_required
def reattempt():
    '''Reattempt tailored quiz'''
    if not current_user.check_student():
        return render_template('errors/error403.html'), 403

    form = ReattemptForm()
    if form.validate_on_submit():
        remove_incorrect_responses(current_user)
        correct, questions = get_response_answer(current_user)   

        return redirect(url_for('quiz.quiz', attempt=correct+4))

    return redirect(url_for('main.dashboard'))

@bp.route('/<int:quizID>/<int:qnNum>', methods=['GET','POST'])
@login_required
def edu_quiz(quizID, qnNum):
    '''Renders user-created quiz'''
    if not current_user.check_student():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_stu(quizID)

    if len(quiz.questions) < qnNum:
        return redirect(url_for('quiz.result', quizID=quizID))

    # If attempting the quiz, get the question to display
    if request.method == 'GET':
        question, options = get_question(current_user, quiz, qnNum - 1)
        if question:
            return render_template('quiz/quiz.html', quiz=quiz, qnNum=qnNum, question=question, options=options, edu=True)

    # If submitting an attempted question
    elif request.method == 'POST':
        submit_response(current_user, request.form)
    return redirect(url_for('quiz.edu_quiz',quizID=quizID,qnNum=qnNum+1))

### UNTESTED
@bp.route('/<int:quizID>/reattempt', methods=['POST'])
@login_required
def reattempt_edu(quizID):
    '''Reattempt educator quiz'''
    if not current_user.check_student():
        return render_template('errors/error403.html'), 403
    quiz = validate_quiz_stu_edu(current_user, quizID)

    form = ReattemptForm()
    if form.validate_on_submit():
        remove_quiz_responses(current_user, quiz)

    return redirect(url_for('quiz.edu_quiz', quizID=quizID, qnNum=1))

@bp.route('/<int:quizID>/result')
@bp.route('/result')
@login_required
def result(quizID=None):
    if not current_user.check_student():
        return render_template('errors/error403.html'), 403
    form = ReattemptForm()
    quiz = None
    if quizID:
        quiz = validate_quiz_stu(quizID)
    correct, questions = get_response_answer(current_user, quizID)
    return render_template('quiz/result.html', questions=questions, correct=correct, quiz=quiz, form=form)

app/templates/quiz/createqn.html
{% from "_formhelpers.html" import render_error %}
{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{url_for('static', filename='content/createstyle.css')}}">
{% endblock %}
{% block content %}
<div class="create-class-wrapper">
    <div class="create-container">
        <form action="" method="post" class="create-form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {% if edit %}
            <h1>Edit Question</h1>
            {% else %}
            <h1>Create A New Quiz</h1>
            {% endif %}
            {{ form.topic(placeholder="Select Topic", class_="center") }}
            {{ render_error(form.topic) }}
            {{ form.qn(size=32, placeholder="Input Question") }}
            {{ render_error(form.qn) }}
            {{ form.op1(size=32, placeholder="Option 1") }}
            {{ render_error(form.op1) }}
            {{ form.op2(size=32, placeholder="Option 2") }}
            {{ render_error(form.op2) }}
            {{ form.op3(size=32, placeholder="Option 3") }}
            {{ render_error(form.op3) }}
            {{ form.op4(size=32, placeholder="Option 4") }}
            {{ render_error(form.op4) }}
            {{ form.corrOp(placeholder="Correct Option") }}
            {{ render_error(form.corrOp) }}
            {{ form.img() }}
            {{ render_error(form.img) }}
            {% if not edit %}
            {{ form.submit(class_="submit-btn") }}
            {% endif %}
            {{ form.complete(class_="submit-btn") }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/quiz/createquizsuccess.html
{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{url_for('static', filename='content/createstyle.css')}}">
{% endblock %}
{% block content %}
<div class="bg-modal">
    <div class="modal-contents quiz-size">
        <h1>Quiz was successfully created!</h1>
        <a href="{{ url_for('quiz.preview_quiz', quizID=quizID) }}" class="route-btn">Preview Quiz</a>
        <!--<a href="#" class="route-btn">Assign Quiz To Class</a>-->
        <a href="{{ url_for('main.dashboard') }}" class="route-btn">Home</a>
    </div>
</div>
{% endblock %}

app/templates/quiz/previewquiz.html
{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='content/quizstyle.css') }}">
{% endblock %}
{% block content %}
<div class="preview-quiz-container" style="overflow: scroll;">
    <div id="quiz">
        <h1 style="margin-top: 3rem;">{{ quiz.name }}</h1>
        <form action="{{ url_for('quiz.deletequiz', quizID=quiz.id) }}" method="post" class="create-form" style="margin: 1rem 0 3rem 0;">
            {{ delQuizForm.hidden_tag() }}
            {{ delQuizForm.submit(class_="delete-btn", placeholder="Delete Quiz") }}
        </form>

        {% for qnID in questions %}
        <h2 id="question">{{ questions[qnID]['question'] }}</h2>
        <form action="{{ url_for('quiz.deleteqn', quizID=quiz.id, qnID=qnID) }}" method="post" class="create-form">
            {{ delQnForm.hidden_tag() }}
            {{ delQnForm.submit(class_="delete-btn float", placeholder="Delete Question") }}
        </form>
        <a href="{{ url_for('quiz.editqn', qnID=qnID) }}" class="edit-btn float"> Edit </a>

        {% if questions[qnID]['image'] %}
        <img src="{{ url_for('static', filename='resources/images/quiz')}}/{{ questions[qnID]['image'] }}" class="pic" alt="">
        {% endif %}

        <ol class="preview-qn">
            {% for optID, opt in questions[qnID]['options'].items() %}
            <li class="options-container" id="options-container">
                <p class="options-prefix">{{loop.index}}</p>
                <label>
                    <input type="radio" class="options" name="option" id="{{optID}}" value="{{optID}}">
                    {% if optID == questions[qnID]['answer'] %}
                    <span class="answer">Answer: {{opt}}</span>
                    {% else %}
                    <span>{{opt}}</span>
                    {% endif %}
                </label>
            </li>

            {% endfor %}
        </ol>
        {% endfor %}

        <a href="{{ url_for('quiz.createqn', quizID=quiz.id) }}" class="edit-btn" style="margin-bottom: 8rem;">Add Question</a>

    </div>

</div>
{% endblock %}

app/templates/quiz/quiz.html
{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='content/quizstyle.css') }}">
{% endblock %}
{% block content %}
<div class="quiz-container">
    <div id="quiz" class="justify-center flex-column">
        {% if edu %}
        <h1>{{ quiz.name }}</h1>
        {% else %}
        <h1>TAILORED QUIZ</h1>
        {% endif %}
        <h2 id="question">{{question}}</h2>

        {% if question.image_file %}
        <img src="{{ url_for('static', filename='resources/images/quiz')}}/{{ question.image_file }}" class="pic" alt="">
        {% endif %}

        {% if edu %}
        <form action="{{ url_for('quiz.edu_quiz', quizID=quiz.id, qnNum=qnNum) }}" method="post">
        {% else %}
        <form action="{{ url_for('quiz.quiz', attempt=attempt) }}" method="post">
        {% endif %}
            <ol>
                {% for o in options %}
                <li class="options-container" id="options-container">
                    <p class="options-prefix">{{loop.index}}</p>
                    <label>
                        <input type="radio" class="options" name="option" id="{{o}}" value="{{o}}" required>
                        <span>{{options[o]}}</span>
                    </label>
                </li>
                <br />

                {% endfor %}
            </ol>
            <p><input class="submit-btn" type="submit" value="SUBMIT"></p>
        </form>
    </div>

</div>
{% endblock %}

app/templates/quiz/result.html
{% extends "base.html" %}
{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='content/quizstyle.css') }}">
{% endblock %}
{% block content %}
<div class="quiz-container" style="overflow-y: scroll; margin-bottom: 8rem;">
    <div id="quiz" class="justify-center flex-column" style="height: 80vh; width: 100vw; margin: 20rem;">
        <h1>Score: <u> {{ correct }}/{{ questions | length }}</u></h1>
        {% if quiz %}
        <h1>{{ quiz.name }}</h1>
        {% else %}
        <h1>General Quiz</h1>
        {% endif %}
        {% for q in questions %}
        <h2 id="question">{{q}}</h2>
        <ol>
            {% for opt in questions[q][0] %}
            <li class="options-container" id="options-container">
                <p class="options-prefix">{{loop.index}}</p>
                <label>
                    <input type="radio" class="options" name="option" id="{{loop.index}}" value="{{opt}}">
                    <span>{{opt}}</span>
                </label>
            </li>
            {% endfor %}

        </ol>
        <div style="margin-bottom: 5rem;">
            <h3>Your Answer: Option {{ questions[q][2] + 1}} </h3>
            {% if questions[q][1] == questions[q][2] %}
            <p style="color: green;">(correct)</p>
            {% else %}
            <p style="color: red;">(wrong)</p>
            {% endif %}
        </div>
        {% endfor %}
        <a href="{{ url_for('main.dashboard') }}" class="edit-btn" style="margin-bottom: 5rem;">Back Home</a>
        {% if quiz %}
        <form action="{{ url_for('quiz.reattempt_edu', quizID=quiz.id) }}" method="post">
        {% else %}
        <form action="{{ url_for('quiz.reattempt') }}" method="post">
        {% endif %}
            {{ form.hidden_tag() }}
            {{ form.submit(class_="edit-btn") }}
        </form>
    </div>
</div>
{% endblock %}